import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class DataInsightCreate {
  @ApiProperty()
  name: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  data: string;
  @ApiProperty()
  visualization_type: string;
  @ApiProperty()
  created_by: string;
  @ApiProperty()
  updated_by: string;
}

export class DataInsight {
  @ApiProperty()
  id: number;
  @ApiProperty()
  name: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  data: string;
  @ApiProperty()
  visualization_type: string;
  @ApiProperty()
  created_by: string;
  @ApiProperty()
  updated_by: string;
}
