/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { Widget, WidgetCreate } from './dtos/Widget.dto';
import { WidgetController } from './Widget.controller';
import { WidgetService } from './Widget.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('WidgetController', () => {
  let controller: WidgetController;
  let spyService: WidgetService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: WidgetService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [WidgetController],
      providers: [WidgetService, ApiServiceProvider],
    }).compile();

    controller = module.get<WidgetController>(WidgetController);
    spyService = module.get<WidgetService>(WidgetService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call WidgetController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call WidgetController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new Widget();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
