/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Widget } from './Widget.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { WidgetService } from './Widget.service';
import { WidgetController } from './Widget.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Widget])],
  providers: [WidgetService],
  exports: [WidgetService],
  controllers: [WidgetController],
})
export class WidgetModule {}
