/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { DataInsight } from './DataInsight.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { DataInsightService } from './DataInsight.service';
import { DataInsightController } from './DataInsight.controller';

@Module({
  imports: [TypeOrmModule.forFeature([DataInsight])],
  providers: [DataInsightService],
  exports: [DataInsightService],
  controllers: [DataInsightController],
})
export class DataInsightModule {}
