/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { DataInsight, DataInsightCreate } from './dtos/DataInsight.dto';
import { DataInsightController } from './DataInsight.controller';
import { DataInsightService } from './DataInsight.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('DataInsightController', () => {
  let controller: DataInsightController;
  let spyService: DataInsightService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: DataInsightService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [DataInsightController],
      providers: [DataInsightService, ApiServiceProvider],
    }).compile();

    controller = module.get<DataInsightController>(DataInsightController);
    spyService = module.get<DataInsightService>(DataInsightService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call DataInsightController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call DataInsightController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new DataInsight();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
