/**
 * This file generated by Apso.
 */
import { WidgetModule } from './Widget/Widget.module';
import { KPIModule } from './KPI/KPI.module';
import { DataInsightModule } from './DataInsight/DataInsight.module';

export default [WidgetModule, KPIModule, DataInsightModule];
