import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class KPICreate {
  @ApiProperty()
  name: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  value: string;
  @ApiProperty()
  target: string;
  @ApiProperty()
  unit: string;
  @ApiProperty()
  created_by: string;
  @ApiProperty()
  updated_by: string;
}

export class KPI {
  @ApiProperty()
  id: number;
  @ApiProperty()
  name: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  value: string;
  @ApiProperty()
  target: string;
  @ApiProperty()
  unit: string;
  @ApiProperty()
  created_by: string;
  @ApiProperty()
  updated_by: string;
}
