/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { KPI, KPICreate } from './dtos/KPI.dto';
import { KPIController } from './KPI.controller';
import { KPIService } from './KPI.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('KPIController', () => {
  let controller: KPIController;
  let spyService: KPIService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: KPIService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [KPIController],
      providers: [KPIService, ApiServiceProvider],
    }).compile();

    controller = module.get<KPIController>(KPIController);
    spyService = module.get<KPIService>(KPIService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call KPIController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call KPIController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new KPI();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
