/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { KPI } from './KPI.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { KPIService } from './KPI.service';
import { KPIController } from './KPI.controller';

@Module({
  imports: [TypeOrmModule.forFeature([KPI])],
  providers: [KPIService],
  exports: [KPIService],
  controllers: [KPIController],
})
export class KPIModule {}
