import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class WidgetCreate {
  @ApiProperty()
  name: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  type: string;
  @ApiProperty()
  data_source: string;
  @ApiProperty()
  settings: string;
  @ApiProperty()
  created_by: string;
  @ApiProperty()
  updated_by: string;
}

export class Widget {
  @ApiProperty()
  id: number;
  @ApiProperty()
  name: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  type: string;
  @ApiProperty()
  data_source: string;
  @ApiProperty()
  settings: string;
  @ApiProperty()
  created_by: string;
  @ApiProperty()
  updated_by: string;
}
